### ISSUE TITLE
Stordis BF2556X-1TA1F - ONIE install - Console hangs

### ISSUE THREAD

**Issue by sonicepk** [rare-freertr/freeRtr#10] opened 2022-08-30 18:52 UTC
Hi all,

I have installed freeRouter v22.7.13-cur on a Stordis BF2556X-1TA1F using the ONIE install and tna-install-experimental at the suggestion of Csaba back in early July. 
 
What I noticed is that on a reboot the console gets stuck with lots of error messages about the ports not being found. I suspect this is related to the Stordis gearbox. 
"2022-08-30 20:03:43.579864 BF_BFRT ERROR - BF_RT_SERVER:table_read:2500 Entry not found in table:$PORT_HDL_INFO Object not found"

If I hit return a few times, I get a strange prompt: "@@@1001!!!###->" I have used exit/quit and eventually a bash terminal starts and you can log in as normal. 

Software: ONIE install with release-1-62-g682d28c-free Debian11_0     5.10.0-8-amd64            stordis_bf2556x_1t         2022-07-13 12:34:15.941461793

Attached is the console output during a reboot. 
[p4-cwt1-stordis-console.txt](https://github.com/rare-freertr/freeRtr/files/9455643/p4-cwt1-stordis-console.txt)

Thanks for your help.

**Comment by mc36** [comment] 2022-09-15 05:31
dear packaging team, please oick this one once you're back...
i oersonally run my stordis in bsp-less mode for a while....
thanks,
cs

**Comment by mc36** [comment] 2022-09-15 11:21
Comments inline.

On Thu, 15 Sep 2022 07:31:54 +0200, mc36 ***@***.***> said:

> dear packaging team, please oick this one once you're back...
> i oersonally run my stordis in bsp-less mode for a while....
> thanks,
> cs


> On 8/30/22 20:52, sonicepk wrote:
>> Hi all,
>> 
>> I have installed freeRouter v22.7.13-cur on a Stordis BF2556X-1TA1F using the ONIE install and tna-install-experimental at the suggestion of Csaba back in early July.
>> 
>> What I noticed is that on a reboot the console gets stuck with lots of error messages about the ports not being found. I suspect this is related to the Stordis gearbox.
>> "2022-08-30 20:03:43.579864 BF_BFRT ERROR - BF_RT_SERVER:table_read:2500 Entry not found in table:$PORT_HDL_INFO Object not found"

This is not related to the gearbox. It's a side-effect of probing for
existing ports when the bf_forwarder starts up (the SDE currently
doesn't support iterating over the elements of the $PORT_HDL_INFO
table so we just query a range of ports and check for existing
entries; hitting a non-existent entry generates these log messages).

>> 
>> If I hit return a few times, I get a strange prompt: "@@@1001 <https://github.com/1001>!!!###->" I have used exit/quit and eventually a bash terminal starts and you can log in as 
>> normal.

This is the Marvell gearbox software that includes a kind of shell
that attaches to the serial port and interfers with the console
login. It's part of the "SAL" (Switch Abstraction Layer") that also
launches bf_switchd on the BF2556. In fact, APS has released new
versions of the BSP and the SAL (still based on SDE 9.7) that fixes
this issue (among other things). I have switched to those versions two
days ago
(https://bitbucket.software.geant.org/projects/RARE/repos/rare-nix/commits/c157e9123d611905586ccee2601c48b9fe1e072b). You
can upgrade to that version of RARE with "tna-install-latest". That
will also move freertr to v22.8.27 (commit 5f077157). As usual, you
can install the newest freertr version with
"tna-install-experimental".

Caveat: I didn't do much testing with the new BSP but it appears to
work ok. However, you should avoid the "tmp_show", "vrail_show" and
"fan_show" commands in the bf_pltfm.chss_mgmt UCLI context. They all
crash bf_switchd (this won't be fixed by APS as they are now working
on the BSP for 9.9.1)

-- 
Alex

**Comment by mc36** [comment] 2022-09-23 16:14
Hi Alex,

Thanks for investigating this. I took your suggestion to do a "tna-install-latest" but I appear to be hitting an SSL issue. I noticed in the archive there was talk of OpenSSL3 but I could not follow the thread. Any suggestions?

DUB0021#tna-install-latest
child 12002 created on 3
child started
INFO: Fetching origin/master from https://bitbucket.software.geant.org/scm/rare/rare-nix.git
Initialized empty Git repository in /tmp/tmp.dbNKdVMbBK/.git/
fatal: unable to access 'https://bitbucket.software.geant.org/scm/rare/rare-nix.git/': OpenSSL SSL_connect: Connectire.geant.org:443
Unexpected error, aborting

process exited with 32768 code
% returned 128
DUB0021#

***@***.***:~$ sudo -i release-manager --list-available
INFO: Checking for release tags of https://bitbucket.software.geant.org/scm/rare/rare-nix.git
Unexpected error, aborting
***@***.***:~$

***@***.***:~$ sudo ping bitbucket.software.geant.org
PING bitbucket.software.geant.org (150.254.211.3) 56(84) bytes of data.
64 bytes from 150.254.211.3 (150.254.211.3): icmp_seq=1 ttl=48 time=41.3 ms

Thanks for your help.

Regards
Eoin
-----Original Message-----

**Comment by mc36** [comment] 2022-09-23 19:15
Hi Eoin,

The topic about OpenSSL3 is unrelated.

I used tna-install-experimental today today and it is basically doing a tna-install-latest + fetching latest great freeRtr from GitUb repository « main » branch 
And it has succeeded. (Against the very same server)

This upgrade occur via the ethernet1 in VRF oob (at least as it is configured)

IMHO you have filtering preventing the SSL establishment.

Can you make sure that you are no filtering in place between the P4 switch and the following hosts: (talking under Alex’s control )

https://bitbucket.software.geant.org
https://cache.nixos.org 
http://p4.cache.nix.net.switch.ch 

If you plan to use GitHub you also need to add:
https://github.com

If you have firewall you can use these FQDN. If you have access list I’m not sure how to resolve dynamic IPs

In case you really want to keep an air gapped upgrade as we usually do in TELCOs you can build a standalone image and use scp to put in on Linux.
Alex is preparing a documentation IIRC.

PS: Connectivity should be enabled between Linux host where freeRtr runs. You can also upgrade with "release-manager" command
     
I hope this help
Frederic

**Comment by mc36** [comment] 2022-09-25 12:58
Hi Eoin,

I see your point. But if you used ONIE installation this should not happen ? (ONIE with DHCP or not…)
Basically ONIE will delete all except existing ONIE partition. Create, format and install a RARE partition with a combo of Debian stable/Nix package manager
I might have missed something then.

In order to better understand and maybe solve your problem let’s try to have a super short VC next week with Alex.

All the best,
Frederic

**Comment by mc36** [comment] 2022-09-25 20:32
Hi Frederic,

Thank you for the hints. Got it sorted. When I removed my ACL on the OOB interface, TLS1.2 worked. No idea why TLS1.2 would not work with https://bitbucket.software.geant.org when the ACL was configured but would work with Github.com.

I have installed the latest experimental release. 
DUB0021#show version                                                                                                                                                   
freeRouter v22.9.25-cur, done by ***@***.***

I can confirm that this resolves the console hanging issue. Thanks you Csaba!!!

Regards
Eoin

________________________________________

**Comment by mc36** [comment] 2022-10-11 09:04
Hi Frederic,

git clone works for TLS1.3 sites and not TLS1.2. For example: git clone works for github but not the Geant bitbucket site. https://bitbucket.software.geant.org only supports TLS1.2 whereas Github supports TLS1.1/1.2/1.3. See below examples.

Cloning into 'rare'...are# GIT_CURL_VERBOSE=1 git clone https://bitbucket.software.geant.org/scm/rare/rare.git
22:56:16.293654 http.c:678              == Info: Couldn't find host bitbucket.software.geant.org in the .netrc file; using defaults
22:56:16.296683 http.c:678              == Info:   Trying 150.254.211.3:443...
22:56:16.338508 http.c:678              == Info: Connected to bitbucket.software.geant.org (150.254.211.3) port 443 (#0)
22:56:16.338895 http.c:678              == Info: ALPN, offering h2
22:56:16.338902 http.c:678              == Info: ALPN, offering http/1.1
22:56:16.347524 http.c:678              == Info: successfully set certificate verify locations:
22:56:16.347534 http.c:678              == Info:  CAfile: /etc/ssl/certs/ca-certificates.crt
22:56:16.347539 http.c:678              == Info:  CApath: /etc/ssl/certs
22:56:16.347729 http.c:678              == Info: TLSv1.3 (OUT), TLS handshake, Client hello (1):
22:56:16.388987 http.c:678              == Info: OpenSSL SSL_connect: Connection reset by peer in connection to bitbucket.software.geant.org:443 
�Ν�
22:56:16.389004 http.c:678              == Info: Closing connection 0
fatal: unable to access 'https://bitbucket.software.geant.org/scm/rare/rare.git/': OpenSSL SSL_connect: Connection reset by peer in connection to bitbucket.software.geant.org:443 
***@***.***:/home/rare# 

***@***.***:~$git clone https://github.com/rare-freertr/freeRtr.git 
remote: Enumerating objects: 101932, done.
remote: Counting objects: 100% (2281/2281), done.
remote: Compressing objects: 100% (437/437), done.
remote: Total 101932 (delta 1790), reused 2252 (delta 1763), pack-reused 99651
Receiving objects: 100% (101932/101932), 28.55 MiB | 11.05 MiB/s, done.
Resolving deltas: 100% (84651/84651), done.
***@***.***:/home/rare# 

This is all probably due to the original install when I did not use dhcp with the ONIE install and I had to add a number of packages after the initial install. 

Regards
Eoin
________________________________________

**Closed** 2022-12-25 04:56 UTC
